# from scipy.spatial.transform import Rotation as SSTR
'Shared utility functions.'
import numpy as np
import torch

# 

def Assert(value, msg):
    assert value, msg


def thrust_to_wrench(thrustForce, thruster_configure):
    """
    thrustForce: n, n_thrusters thrust force generated by each propeller in each env
    thruster_configure: 6, n_thrusters thruster configuration matrix
    return: n,6 wrench in body frame generated by all thrusters in each env
    """
    return torch.matmul(thruster_configure, thrustForce.unsqueeze(-1)).squeeze(-1)


def wrench_to_thrust(
    wrench: torch.Tensor,
    thruster_configure: torch.Tensor,
    reg: float = 1e-6,
) -> torch.Tensor:
    """
    Convert desired body-frame wrench to thruster forces via
    regularized least-squares allocation.

    wrench: (n, 6)
    thruster_configure: (6, n_thrusters)
    return: (n, n_thrusters)
    """
    # B: (6, N)
    B = thruster_configure
    BT = B.transpose(0, 1)  # (N, 6)
    N = B.shape[1]

    # (N, N)
    BTB = BT @ B
    BTB_reg = BTB + reg * torch.eye(N, device=B.device, dtype=B.dtype)

    # (N, 6)
    pinv_term = torch.linalg.solve(BTB_reg, BT)

    # (n, N) = (n, 6) @ (6, N)
    thrust = wrench @ pinv_term.T

    return thrust


def cmd_to_pwm_to_rpm(
    cmd: torch.Tensor,
    rpm_dir: torch.Tensor = torch.tensor([1, -1, -1, 1, 1, -1, 1, -1]),
) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Convert normalized action cmd [-1,1] to PWM and then to RPM using fitted model.
    Args:
        cmd: Tensor of shape (n_envs, n_thrusters)
             normalized commands in [-1,1], where -1 is full reverse, 1 is full forward.
        rpm_dir: Tensor of shape (n_thrusters) indicating the direction of the thrusters' rotation.
                 if rpm>0, then that thruster rotates clockwise, else counter-clockwise.
                 this parmaeter is used to rectify the RPM direction of the thrusters.

    Returns:
        pwm: Tensor of same shape as cmd, PWM values in range [1100,1900]
        rpm: Tensor of same shape as cmd, corresponding RPM [-4000,4000]
    """
    # deadzone
    cmd = cmd.clone()
    cmd[torch.abs(cmd) < 0.05] = 0.0
    # cmd -> PWM
    pwm = cmd * 400.0 + 1500.0  # -1 -> 1100, 0 -> 1500, 1 -> 1900
    rpm = torch.zeros_like(pwm)
    upper_mask = pwm > 1520
    lower_mask = pwm < 1480
    if torch.any(upper_mask):
        pwm_upper = pwm[upper_mask]
        rpm[upper_mask] = -0.030097 * pwm_upper**2 + 110.160 * pwm_upper - 97959.33
    if torch.any(lower_mask):
        pwm_lower = pwm[lower_mask]
        rpm[lower_mask] = 0.017175 * pwm_lower**2 - 36.601 * pwm_lower + 16286.06

    # print(rpm.shape, rpm_dir.shape)
    rpm *= rpm_dir.to(rpm.device)
    return pwm, rpm


if __name__ == "__main__":
    TAM = torch.tensor(
        [
            [1.0, 1.0, 1.0, 1.0],  
            [0.0, 0.0, 0.0, 0.0],  # Fy
            [0.0, 0.0, 0.0, 0.0],  # Fz
            [0.0, 0.0, 0.0, 0.0],  # Mx
            [0.5, -0.5, 0.5, -0.5],  
            [0.5, 0.5, -0.5, -0.5],  # Mz
        ],
        device="cuda:0",
    )
    current_thrusts = torch.tensor(
        [
            [10.0, 10.0, 10.0, 10.0],  
            [10.0, -10.0, 10.0, -10.0],  
        ],
        device="cuda:0",
    )
    wrench = thrust_to_wrench(current_thrusts, TAM)
    print(wrench.shape)  # torch.Size([2, 6])
    print(wrench)
