"""
Thruster rotational speed to force conversion functions
if speed>0 Then the propeller>0 too.
input rotation speed range: -4000rpm, 4000 rpm
output thrust force range: -40N, 40N
"""

import torch
import numpy as np
from scipy.interpolate import interp1d


class ConversionFunction:
    def __init__(self):
        self.force_dir: torch.Tensor = torch.tensor([1, 1, -1, -1, 1, -1, -1, -1])

    def convert(self, dynamicState: torch.tensor) -> torch.tensor:
        """
        dynamicState : n,n_thrusters, rotation speed(state)of each propeller in each env
        return: n,n_thrusters, thrust force generated by each propeller in each env
        """
        raise NotImplementedError()

    def set_redify_factor(
        self, force_dir: torch.Tensor = torch.tensor([1, 1, -1, -1, 1, -1, -1, -1])
    ):
        """
        for diffirent thruster, force direction maybe different with thruster rotation direction.
        this function can set the force direction redify factor.
        """
        self.force_dir = force_dir.clone()

    def inv_convert(self, force: torch.tensor) -> torch.tensor:
        """
        force : n,n_thrusters, thrust force generated by each propeller in each env
        return: n,n_thrusters, rotation speed(state)of each propeller in each env
        """
        raise NotImplementedError()


class ConversionFunctionBasic(ConversionFunction):
    def __init__(self, rotorConstant: float):
        super().__init__()
        self.rotorConstant = rotorConstant

    def convert(self, dynamicState: torch.tensor) -> torch.tensor:
        force_b = self.rotorConstant * torch.abs(dynamicState) * dynamicState
        force_b *= self.force_dir.to(force_b.device)
        return force_b

    def inv_convert(self, force: torch.tensor) -> torch.tensor:
        dynamicState = torch.sqrt(torch.abs(force) / self.rotorConstant)
        dynamicState *= torch.sign(force)
        dynamicState *= self.force_dir.to(dynamicState.device)
        return dynamicState


class ConversionFunctionBessa(ConversionFunction):
    def __init__(
        self, rotorConstantL: float, rotorConstantR: float, deltaL: float, deltaR: float
    ):
        self.rotorConstantL = rotorConstantL
        self.rotorConstantR = rotorConstantR
        self.deltaL = deltaL
        self.deltaR = deltaR

    def convert(self, dynamicState: torch.tensor) -> torch.tensor:
        basic = dynamicState * torch.abs(dynamicState)
        mask = (basic <= self.deltaL).float()
        force_b = self.rotorConstantL * (
            basic - self.deltaL
        ) * mask + self.rotorConstantR * (basic - self.deltaR) * (1 - mask)
        return force_b

    def inv_convert(self, force: torch.tensor) -> torch.tensor:
        basic = torch.zeros_like(force)
        mask = (force <= self.rotorConstantL * (-self.deltaL)).float()
        basic = (force / self.rotorConstantL + self.deltaL) * mask + (
            force / self.rotorConstantR + self.deltaR
        ) * (1 - mask)
        dynamicState = torch.sqrt(torch.abs(basic))
        dynamicState *= torch.sign(basic)
        return dynamicState


class ConversionFunctionInterp(ConversionFunction):
    'Create an interpolated thrust-conversion function from tabular data.'

    def __init__(
        self,
        inputValues: list | np.ndarray,
        outputValues: list | np.ndarray,
        type: str = "linear",
    ):
        x = inputValues
        y = outputValues
        self.BuildInterpolator(x, y, type)

    def convert(self, dynamicState: torch.tensor) -> torch.tensor:
        force_b = torch.from_numpy(
            self._interpolator(dynamicState),
            device=dynamicState.device,
            dtype=torch.float32,
        )
        return force_b

    def BuildInterpolator(self, x, y, type):
        self._interpolator = interp1d(
            x, y, kind=type, bounds_error=False, fill_value=(y[0], y[-1])
        )
        self._inv_interpolator = interp1d(
            y, x, kind=type, bounds_error=False, fill_value=(x[0], x[-1])
        )

    def GetTable(self):
        return self._interpolator

    def inv_convert(self, force: torch.tensor) -> torch.tensor:
        dynamicState = torch.from_numpy(
            self._inv_interpolator(force),
            device=force.device,
            dtype=torch.float32,
        )
        return dynamicState


ThrusterConversionMap = {
    "Basic": ConversionFunctionBasic,
    "Bessa": ConversionFunctionBessa,
    "Interp": ConversionFunctionInterp,
}
